#! /usr/bin/python3

import subprocess
import shutil
import os

def download_snap (directory, channel):
    cmd = ['snap', 'download', 'fwupd']
    if channel is not None:
        cmd += ['--channel', channel]
    if 'DEBUG' in os.environ:
        print(cmd)
    subprocess.run (cmd, cwd=directory, check=True)
    for f in os.listdir (directory):
        # the signatures associated with the snap
        if f.endswith(".assert"):
            shutil.move (os.path.join(directory, f), os.path.join(directory, 'fwupd.assert'))
        # the snap binary itself
        elif f.endswith(".snap"):
            shutil.move (os.path.join(directory, f), os.path.join(directory, 'fwupd.snap'))

if __name__ == '__main__':
    download_snap ('.', None)
